// <auto-generated />
using Data.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.EFCore.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230616063657_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.GuildData", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("InlineTagsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("InlineTagsPrefix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("$");

                    b.HasKey("GuildId");

                    b.ToTable("GuildData");
                });

            modelBuilder.Entity("Data.Entities.Tags.BaseTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<ulong?>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseTag");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Data.Entities.Tags.AliasTag", b =>
                {
                    b.HasBaseType("Data.Entities.Tags.BaseTag");

                    b.Property<long>("ReferencedTagId")
                        .HasColumnType("bigint");

                    b.HasIndex("ReferencedTagId");

                    b.HasDiscriminator().HasValue("AliasTag");
                });

            modelBuilder.Entity("Data.Entities.Tags.MessageTag", b =>
                {
                    b.HasBaseType("Data.Entities.Tags.BaseTag");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasDiscriminator().HasValue("MessageTag");
                });

            modelBuilder.Entity("Data.Entities.Tags.AliasTag", b =>
                {
                    b.HasOne("Data.Entities.Tags.BaseTag", "ReferencedTag")
                        .WithMany("Aliases")
                        .HasForeignKey("ReferencedTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferencedTag");
                });

            modelBuilder.Entity("Data.Entities.Tags.BaseTag", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
