//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Dispatcher.Mappers.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MappingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MappingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Dispatcher.Mappers.Common.MappingResources", typeof(MappingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18+ 🔞.
        /// </summary>
        internal static string GuildData_AdultAllowed {
            get {
                return ResourceManager.GetString("GuildData_AdultAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID сервера - {0}.
        /// </summary>
        internal static string GuildData_GuildId {
            get {
                return ResourceManager.GetString("GuildData_GuildId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер {0}.
        /// </summary>
        internal static string GuildData_GuildName {
            get {
                return ResourceManager.GetString("GuildData_GuildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Префикс тегов 🔍.
        /// </summary>
        internal static string GuildData_InlineTagPrefix {
            get {
                return ResourceManager.GetString("GuildData_InlineTagPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Быстрые теги ⚡.
        /// </summary>
        internal static string GuildData_InlineTags {
            get {
                return ResourceManager.GetString("GuildData_InlineTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌.
        /// </summary>
        internal static string No_Emoji {
            get {
                return ResourceManager.GetString("No_Emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No_String {
            get {
                return ResourceManager.GetString("No_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер.
        /// </summary>
        internal static string Tag_GuildId {
            get {
                return ResourceManager.GetString("Tag_GuildId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тег - {0}.
        /// </summary>
        internal static string Tag_Name {
            get {
                return ResourceManager.GetString("Tag_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владелец.
        /// </summary>
        internal static string Tag_OwnerId {
            get {
                return ResourceManager.GetString("Tag_OwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оригинал.
        /// </summary>
        internal static string Tag_ReferencedTagName {
            get {
                return ResourceManager.GetString("Tag_ReferencedTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        internal static string Tag_Type {
            get {
                return ResourceManager.GetString("Tag_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровнь доступа 🔒.
        /// </summary>
        internal static string UserData_AccessLevel {
            get {
                return ResourceManager.GetString("UserData_AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный лимит тегов ❓.
        /// </summary>
        internal static string UserData_CustomTagLimit {
            get {
                return ResourceManager.GetString("UserData_CustomTagLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лимит тегов 📃.
        /// </summary>
        internal static string UserData_TagLimit {
            get {
                return ResourceManager.GetString("UserData_TagLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID пользователя - {0}.
        /// </summary>
        internal static string UserData_UserId {
            get {
                return ResourceManager.GetString("UserData_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь {0}.
        /// </summary>
        internal static string UserData_UserName {
            get {
                return ResourceManager.GetString("UserData_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅.
        /// </summary>
        internal static string Yes_Emoji {
            get {
                return ResourceManager.GetString("Yes_Emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes_String {
            get {
                return ResourceManager.GetString("Yes_String", resourceCulture);
            }
        }
    }
}
